### ISSUE TITLE
potential bug: `wrap` now autostarting iterators that were previously not autostarted prior to optimisation work

### ISSUE THREAD

**Issue by jeswr** [RubenVerborgh/AsyncIterator#88] opened 2022-09-13 13:35 UTC
Placeholder - will try create a minimal example or debug tommorow :)

**Comment by jeswr** [comment] 2022-09-20 05:14
On buggy case that I encountered today is the following which blocks on the second line

```ts
const iter = wrap(wrap([1, 2, 3], { autoStart: true }))
await iter.toArray()
```

cc @jacoscaz

**Comment by RubenVerborgh** [comment] 2022-09-20 09:47
Note that I slightly changed `toArray` behavior in 174d87cb: I found a bug where iterators that had already ended would cause a hang. Probably unrelated though.

**Comment by jacoscaz** [comment] 2022-09-21 07:27
Given the conversation around https://github.com/RubenVerborgh/AsyncIterator/pull/45, should we address this before that merge or after?

**Comment by RubenVerborgh** [comment] 2022-09-21 08:23
I think before; this seems like a bug that we still want fixed in the current vminor.

**Comment by jacoscaz** [comment] 2022-09-21 10:15
@jeswr I'm not sure that is related to `autoStart`, actually. If `autoStart` is passed as an option to `wrap()`, regardless of its value, then the source is passed on to the `TransformIterator` constructor: 

https://github.com/RubenVerborgh/AsyncIterator/blob/915a85734824809cc65b189d3e095c590da1334b/asynciterator.ts#L2127-L2128

However, with the current `main` the following doesn't work:

```typescript
const iter = new TransformIterator([1, 2, 3])
const res = await iter.toArray();
```

Therefore, I think what's wrong here is:

1) the fact that we're passing an array as-is to `TransformIterator`
2) the fact that we're not catching 1) as a mistake even though we're using TypeScript

Which is not to say that the premise of this issue is wrong. The default behavior if no `autoStart` option is provided might have changed, indeed.

**Comment by RubenVerborgh** [comment] 2022-09-21 10:20
> 1. the fact that we're passing an array as-is to `TransformIterator`

Indeed; that is not supported. I would have expected the type system to catch it, and `TransformIterator` to throw (because it cannot attach listeners).

**Comment by RubenVerborgh** [comment] 2022-09-21 10:22
Is it this? 25085c4a5b2f5fa5f15979cc8f9266e42465cfa3 / https://github.com/RubenVerborgh/AsyncIterator/pull/80

**Comment by jacoscaz** [comment] 2022-09-21 10:24
I think the issue is at line 2128 (see above), which is in the body of `wrap()`. `source` (which might be an array) is being cast to `MaybePromise<AsyncIterator<T>>`, thus bypassing type checks in the `TransformIterator` constructor.

**Comment by RubenVerborgh** [comment] 2022-09-21 10:28
I think the intention of the original `wrap` typing was to not accept `autoStart` options for `IterableSource`, and thus only for `AsyncIterator`. So now the question is: do we adhere to the intended typings, or do we update the function such that options are possible also for `IterableSource`?

In any case, it does not seem like a regression because this would not have worked before the `wrap` rewrite.

**Comment by jacoscaz** [comment] 2022-09-21 10:33
IMHO and looking very long-term, the `autoStart` option should disappear (https://github.com/RubenVerborgh/AsyncIterator/issues/25) . When working on new features I would try to limit support for it as much as possible while keeping backward compatibility when it comes to minor versions. I would adhere to the intended typings, disallowing `autoStart` for `IterableSource`s.

**Comment by RubenVerborgh** [comment] 2022-09-21 10:35
`autoStart` will absolutely disappear in the next vmajor.

@jeswr Are you okay with restricting the typings, so reverting the solution to #80? (Which begs the question, for which kinds of arguments _do_ we want to allow the `autoStart` option?)

**Comment by jeswr** [comment] 2022-09-21 10:53
> for which kinds of arguments do we want to allow the autoStart option?

In #45 I renamed it to `preBuffer` (I think @RubenVerborgh s suggestion). It should only be available on iterators that extend the buffered iterator. When true the buffer will be pre-filled before the first `.read()` call; when `false` the buffer will remain empty until the first `.read()` call is made.

**Comment by jeswr** [comment] 2022-09-21 10:55
In the case of `wrap` I think we should remove the options parameter entirely to be completely honest. By setting `maxBuffer` or `preBuffer` users can suddenly introduce buffering even if they are just wrapping synchronous iterators.

I think it is better to force users to use the `TransformIterator` in the limited cases where they actually want to use it (I imagine there are less than a handful across all of Comunica where we would need to do this); and include a few docs on upgrading.

**Comment by RubenVerborgh** [comment] 2022-09-21 11:22
> remove the options parameter entirely to be completely honest

But we can't for backward compatibility reasons.

> It should only be available on iterators that extend the buffered iterator.

…and we probably don't want this kind of inheritance anymore, btw. I think we should do away with `BufferedIterator` as a base class, and only have it as a decorator where it is needed.

**Comment by RubenVerborgh** [comment] 2022-09-21 11:37
@jacoscaz Path of least resistance seems to be accepting arrays; see #91.

**Comment by jeswr** [comment] 2022-09-21 11:42
> But we can't for backward compatibility reasons.

This suggestion was for the next vmajor

**Closed as completed** 2022-09-21 11:46 UTC

**Comment by jacoscaz** [comment] 2022-09-21 14:41
> …and we probably don't want this kind of inheritance anymore, btw. I think we should do away with BufferedIterator as a base class, and only have it as a decorator where it is needed.

Yes, buffering and transforms are orthogonal concerns and addressing them independently of one another might be a good idea.
